import checkListIcon from '../../assets/checklist-icon.png'

export default function ProjectOverview({ title }) {
    return (
        <section id="dashboard-project-view" className="stream-content extracted-style-18" style={{ display: 'none', }}>
            <div className="dashboard-page-header">
                <img src={checkListIcon} alt="Checklist" />
                <h1>{title}</h1>
            </div>

            <div className="groups-grid" id="groups-container">
                {/* Group cards will be generated by JS */}
            </div>
        </section>
    );
}